services:
  
  wt-database:
    image: rimvanvliet/wt-database:0.0.1
    container_name: wt-database
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_USER=wt
      - POSTGRES_PASSWORD=wt
      - POSTGRES_DB=wt
    volumes:
      - wt-database:/bitnami/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  wt-database: